name: digeexplore
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  video_player: ^2.4.4
  sqflite: ^2.0.0+3
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/sistema_digestorio.png
    - assets/images/sistemaDigestorioImagem.png
    - assets/images/sistemaDigestorioDemarcadoBoca.png
    - assets/images/sistemaDigestorioDemarcadoEsofago.png
    - assets/images/sistemaDigestorioDemarcadoEstomago.png
    - assets/images/sistemaDigestorioDemarcadoFigado.png
    - assets/images/sistemaDigestorioDemarcadoIntestinos.png
    - assets/images/jogoMemoria.png
    - assets/images/quiz.png
    - assets/images/memoria.png
    - assets/images/boca.png
    - assets/images/estomago.png
    - assets/images/figado.png
    - assets/images/intestinos.png
    - assets/videos/video_conteudo.mp4
    - assets/videos/tutorial_memoria.mp4
    - assets/videos/tutorial_quiz.mp4
    - assets/images/pancreas.png
